name: Check Current Version

on:
  workflow_call:
    outputs:
      version:
          value: ${{ jobs.check-version.outputs.version }}
      version_changed:
          value: ${{ jobs.check-version.outputs.version_changed }}

jobs:
  check-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      version_changed: ${{ steps.version.outputs.version_changed }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        # fetch-depth: 0 only when full history is absolutely required.
        # It is necessary for version/tag comparison (e.g., git tag -l),
        # the default fetch-depth: 1 is for shallow clone
        fetch-depth: 0

    - name: Read VERSION file and check for changes
      id: version
      run: |
        if [ ! -f VERSION ]; then
          echo "VERSION file not found!"
          exit 1
        fi

        CURRENT_VERSION=$(cat VERSION | tr -d '\n')
        echo "version=$CURRENT_VERSION" >> $GITHUB_OUTPUT

        # Check if this version tag already exists
        if git tag -l | grep -q "^v$CURRENT_VERSION$"; then
          echo "version_changed=false" >> $GITHUB_OUTPUT
          echo "Tag v$CURRENT_VERSION already exists"
        else
          echo "version_changed=true" >> $GITHUB_OUTPUT
          echo "New version detected: $CURRENT_VERSION"
        fi

        # Determine if we should build
        if [[ "${{ github.event_name }}" == "schedule" ]] || \
           [[ "${{ github.event_name }}" == "workflow_dispatch" ]] || \
           [[ "${{ github.event_name }}" == "pull_request" ]] || \
           [[ "${{ steps.version.outputs.version_changed }}" == "true" ]]; then
          echo "should_build=true"
        else
          echo "should_build=false"
        fi
